version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    healthcheck:
      test: nc -z localhost 5432
  core:
    build:
      context: ./core_banking
    environment:
      - MIX_ENV=prod 
    ports:
      - 8080:8080
